import React, { useEffect } from "react";

const Story = () => {
  useEffect(() => {
    window.scrollTo({
      top: 0,
      behavior: "instant",
      left: 0,
    });
  }, []);
  return (
    <>
      <div className="flex flex-col px-[5rem] bg-gray-200">
        <p className="flex justify-center pt-10 text-gray-500">ABOUT US</p>
        <div className="text-xs pt-20">
          <p>
            BLUORNG, PRONOUNCED AS "BLUE~ORANGE," TRANSCENDS THE CONVENTIONAL
            BOUNDARIES OF FASHION, EMBODYING A HAUTE COUTURE ETHOS THAT CAPTURES
            THE SPIRIT OF THE MODERN LIFESTYLE. CONCEIVED BY THE MINDS OF
            SIDDHANT SABHARWAL AND MOKAM SINGH, THE BRAND MADE ITS MARK WITH THE
            UNVEILING OF ITS PREMIER STUDIO IN DELHI IN DECEMBER 2020, AND SINCE
            THEN, IT HAS BEEN ON AN UNSTOPPABLE JOURNEY OF REDEFINING THE
            FASHION LANDSCAPE IN INDIA.
          </p>
          <p className="pt-5">
            WHAT SETS BLUORNG APART IS OUR ABILITY TO SEAMLESSLY BLEND OPULENCE
            WITH EVERYDAY FUNCTIONALITY. OUR COLLECTIONS ARE METICULOUSLY
            CURATED TO BRING FORTH A DYNAMIC FUSION OF VIBRANT HUES, ORIGINAL
            GRAPHICS, AND IMPACTFUL BRANDING. IN ESSENCE, BLUORNG HAS BECOME THE
            EPICENTRE OF STREETWEAR CULTURE IN INDIA, RESONATING WITH A
            DEDICATED COMMUNITY DRAWN TO ITS INNATE APPEAL AND OUR BRAND'S
            UNWAVERING COMMITMENT TO QUALITY AND AUTHENTICITY.
          </p>
          <p className="pt-5">
            AT BLUORNG, WE VIEW FASHION AS A CANVAS FOR STORYTELLING, AND EACH
            PIECE IS A WORK OF ART THAT NARRATES A TALE OF CRAFTSMANSHIP AND
            INNOVATION. OUR DIVERSE RANGE, FROM TEES AND HOODIES TO CARGO PANTS
            AND LEATHER BAGS, CONTINUALLY CHALLENGES THE NORMS OF CREATIVITY
            WITHIN ONE'S WARDROBE. THE BRAND'S EXCLUSIVE RELEASES, OFFERED IN
            LIMITED QUANTITIES, HAVE BECOME A PHENOMENON, CREATING ANTICIPATION
            AND EXCITEMENT AMONG OUR ENTHUSIASTIC COMMUNITY.
          </p>
          <p className="pt-5">
            ONE OF BLUORNG'S DISTINCTIVE FEATURES IS OUR COMMITMENT TO
            INCLUSIVITY THROUGH SIZE-INCLUSIVE CLOTHING. WE FIRMLY BELIEVE THAT
            FASHION IS FOR EVERYONE, AND OUR MISSION IS TO PROVIDE TOP-TIER
            APPAREL THAT NOT ONLY SHOWCASES CUTTING-EDGE DESIGNS BUT ALSO CATERS
            TO EVERY INDIVIDUAL, REGARDLESS OF WHAT THEY BELIEVE IN.
          </p>
          <p className="pt-5">
            AS WE CONTINUE TO MAKE WAVES IN THE INDIAN FASHION SCENE, BLUORNG'S
            STORY EXPANDS GLOBALLY. OUR BRAND-OWNED STORES IN DELHI, MUMBAI, AND
            HYDERABAD, ALONG WITH OUR OFFICIAL WEBSITE, SERVE AS EXCLUSIVE
            PLATFORMS FOR ENTHUSIASTS TO EXPLORE AND ACQUIRE OUR CREATIONS. WITH
            WORLDWIDE SHIPPING, BLUORNG EXTENDS ITS REACH BEYOND BORDERS,
            CONNECTING WITH FASHION AFICIONADOS AROUND THE GLOBE.
          </p>
          <p className="pt-5">
            IN ESSENCE, BLUORNG IS MORE THAN JUST A BRAND; IT'S A MOVEMENT, A
            REVOLUTION IN PREMIUM COMFORT STYLE THAT DRAWS INSPIRATION FROM
            NATURE AND THRIVES ON THE CELEBRATION OF DIVERSITY AND
            INDIVIDUALITY. AS DESIGNER-FOUNDER'S, WE ARE EXCITED ABOUT THE
            FUTURE CHAPTERS WE WILL WRITE AND THE BOLD STATEMENTS WE WILL
            CONTINUE TO MAKE IN THE WORLD OF FASHION. IN THE REALM OF
            CONTEMPORARY FASHION, BLUORNG STANDS AS A VISIONARY FORCE, PUSHING
            THE BOUNDARIES OF STYLE AND COMFORT TO NEW HEIGHTS. AS
            DESIGNER-FOUNDERS, WE ARE THRILLED TO SHARE THE UNIQUE APPROACH
            BLUORNG TAKES IN PIONEERING A SHIFT TOWARDS PREMIUM COMFORT STYLE IN
            INDIA, INFUSED WITH ELEMENTS OF NATURE AND A COMMITMENT TO EMBRACING
            HUMAN EMOTIONS AS INDIVIDUALS.
          </p>
        </div>
        <div className="pt-5 ">ABOUT THE FOUNDERS:</div>
        <div className="text-xs">
          <p className="pt-5">
            SIDDHANT SABHARWAL AND MOKAM SINGH FIRST CROSSED PATHS AT DESIGN
            SCHOOL, WHERE THEIR SHARED PASSION FOR FASHION AND STREETWEAR
            IGNITED A COLLABORATIVE SPARK. RECOGNIZING A VOID IN THE MARKET FOR
            A DYNAMIC GLOBAL BRAND ORIGINATING FROM INDIA, THEY SEIZED THE
            OPPORTUNITY TO BRIDGE THIS GAP. TOGETHER, THEY EMBARKED ON THE
            JOURNEY TO ESTABLISH THEIR OWN PREMIUM STREETWEAR LABEL, APTLY NAMED
            BLUORNG.
          </p>
          <p className="pt-5">
            LEVERAGING MOKAM'S KEEN DESIGN SENSIBILITIES AND SIDDHANT'S
            ATTENTION TO DETAIL, THE DUO METICULOUSLY CRAFTED AN IDENTITY FOR
            BLUORNG THAT PRIORITISED UNIQUE STREETWEAR PRODUCTS WITH AN
            UNWAVERING FOCUS ON QUALITY OVER QUANTITY. OVER TIME, BLUORNG HAS
            EVOLVED INTO ONE OF INDIA'S MOST SUCCESSFUL PREMIUM STREETWEAR
            BRANDS, STEADFAST IN ITS COMMITMENT TO COMMUNITY-BUILDING.
          </p>
          <p className="pt-5 pb-10">
            THE SERENDIPITOUS MEETING AT DESIGN SCHOOL AND THE SUBSEQUENT
            DECISION TO LAUNCH BLUORNG HAVE BECOME PIVOTAL MOMENTS IN THE
            COUNTRY'S FASHION LANDSCAPE, UNDERSCORING THE SIGNIFICANCE OF
            COLLABORATION AND VISIONARY THINKING IN THE ESTABLISHMENT OF A
            THRIVING BRAND.
          </p>
        </div>
      </div>
    </>
  );
};

export default Story;
